export const formdata = [
  {
    id: 1,
    inputTitle: "event_name",
    labelTitle: "Event name",
    inputType: "text",
    placeholder: "",
    required: true,
    value: "",
  },
  {
    id: 2,
    inputTitle: "host_name",
    labelTitle: "Host Name",
    inputType: "text",
    placeholder: "",
    required: true,
    value: "",
  },
  {
    id: 3,
    inputTitle: "start_date",
    labelTitle: "Start Date",
    inputType: "date",
    placeholder: "",
    required: true,
    value: "",
  },
  {
    id: 4,
    inputTitle: "end_date",
    labelTitle: "End Date",
    inputType: "date",
    placeholder: "",
    required: true,
    value: "",
  },
  {
    id: 5,
    inputTitle: "location",
    labelTitle: "Location",
    inputType: "text",
    placeholder: "",
    required: false,
    value: "",
  },
  {
    id: 6,
    inputTitle: "event_photo",
    labelTitle: "Event Photo",
    inputType: "file",
    placeholder: "",
    required: true,
    value: "",
  },
];
